[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm install --legacy-peer-deps --force"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s dist -l 3000"
