services:
  #todo: add separate database connection for keycloak instead of h2
  #todo: configure https
  keycloak:
    container_name: security-server
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --import-realm
    ports:
      - "8081:8081"
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8081
      KC_HOSTNAME: http://localhost:8081
      KC_HOSTNAME_STRICT: false
      KC_HTTP_RELATIVE_PATH: /
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}'" ]
      interval: 5s
      timeout: 5s
      retries: 10

  atelier-backend:
    container_name: atelier-backend
    build:
      dockerfile: Dockerfile
    image: atelier-backend:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file: .env
    volumes:
      - atelier-files:/atelier/storage
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:8080/actuator/health | grep UP || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy

volumes:
  pgdata:
  keycloak_data:
  atelier-files:
