[phases.setup]
# Nixpacks installe ces paquets dans le mÃªme profile Nix.
# IMPORTANT: ne mettre qu'UN seul JDK ici (sinon "collision" entre OpenJDKs).
nixPkgs = ["jdk21", "bash", "curl", "cacert"]

[phases.build]
cmds = ["./mvnw -B -DskipTests clean package"]

[start]
cmd = "java -jar target/atelier-0.0.1-SNAPSHOT.jar"

